Path argument in paste, reporting copy status

diff --git a/copy b/copy
--- a/copy
+++ b/copy
@@ -6,25 +6,22 @@ copyfile="/tmp/copypaste.$USER"
 touch $copyfile
 rm $copyfile
 
-if [[ $# -eq 0 ]];
-then
+if [ $# -eq 0 ]; then
     echo "Nothing to copy!"
-    exit
+    exit 1
 fi
 
 for var in "$@"
 do
-    if [[ "$var" = /* ]];
-    then
-	filename="$var"
-    else
-	filename="$cwd/$var"
+    if [[ "$var" = /* ]]; then # Absolute path
+    	filename="$var"
+    else                       # Relative path
+    	filename="$cwd/$var"
     fi
     
-    if [ ! -f "$filename" ];
-    then
-	echo "$filename: File not found!"
+    if [ ! -f "$filename" ]; then
+    	echo "$filename: File not found!"
     else
-	echo "$filename" >> $copyfile	
+	    echo "$filename" >> $copyfile	
     fi
 done
diff --git a/paste b/paste
--- a/paste
+++ b/paste
@@ -2,13 +2,26 @@
 
 copyfile="/tmp/copypaste.$USER"
 
-if [ ! -f "$copyfile" ];
-then
+if [ ! -f "$copyfile" ]; then
     echo "Nothing to paste!"
-    exit
+    exit 1
+fi
+
+if [ "$#" -eq 1 ]; then
+    outpath="$1"
+elif [ "$#" -eq 0 ]; then
+    outpath="."
+else
+    echo "More than 1 argument (usage: \"paste [outdir]\")"
+    exit 1
 fi
 
 while read -r line;
 do
-    cp -a "$line" .
+    cp -a "$line" "$outpath"
+    if [ "$?" -eq 0 ]; then
+        echo "Copied $line to $outpath"
+    else
+        echo "Failed to copy $line to $outpath"
+    fi
 done < $copyfile
